###############################################################################
#
# Makefile for a script (e.g. Python), project 11
#
###############################################################################

all:
	chmod a+x JackCompiler

tar: JackCompiler JackCompiler.py JackTokenizer.py CompilationEngine.py SymbolTable.py VMWriter.py README Makefile
	tar cf project11.tar $^

